Bonjour,

Une nouvelle mission est disponible sur votre espace personnel.
Détails de la mission :
	Type : <?= $mission->getType(); ?>.
	Date : <?= $mission->getDateFormatted(); ?>.
	Départ : <?= $mission->getName(); ?>.
	Debut : <?= $mission->getStartFormatted(); ?>.
	Fin : <?= $mission->getEndFormatted(); ?>.
<?php if ($mission->isAstreinte()): ?>
	Dosponibilité : <?= $mission->getArrival(); ?>.
<?php else: ?>
	Arrivée : <?= $mission->getArrival(); ?>.
	Train : <?= $mission->getTrain(); ?>.

Suivi Info trafic : <?= $mission->getLink(); ?>.
<?php endif; ?>
