Bonjour,

Une nouvelle mission est disponible sur votre espace personnel.
Détails de la mission :
	Type : <?= $mission->getType(); ?>.
	Date : <?= $mission->getDateFromatted(); ?>.
	Départ : <?= $mission->getName(); ?>.
	Debut : <?= $mission->getStartFromatted(); ?>.
	Fin : <?= $mission->getEndFromatted(); ?>.
<?php if ($mission->getArrival()) : ?>
	Arrivée : <?= $mission->getArrival(); ?>.
<?php endif; ?>
