Bonjour,

Une nouvelle mission est disponible sur votre espace personnel.
Détails de la mission :
	Type : <?= $mission->getType(); ?>.
	Date : <?= $mission->getDate()->format('d/m/Y'); ?>.
	Départ : <?= $mission->getName(); ?>.
	Debut : <?= $mission->getStart()->format('H:i'); ?>.
	Fin : <?= $mission->getEnd()->format('H:i'); ?>.
<?php if ($mission->getArrival()) : ?>
	Arrivée : <?= $mission->getArrival(); ?>.
<?php endif; ?>


